//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarputGayriMenkul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public Advert()
        {
            this.AdvertEnvironmentFeature = new HashSet<AdvertEnvironmentFeature>();
            this.AdvertExteriorFeature = new HashSet<AdvertExteriorFeature>();
            this.AdvertInternalFeature = new HashSet<AdvertInternalFeature>();
            this.Picture = new HashSet<Picture>();
        }
    
        public int AdvertID { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public int SquareMeters { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int QuarterID { get; set; }
        public int CategoryID { get; set; }
        public int VarietyID { get; set; }
        public Nullable<int> CurrencyTypeID { get; set; }
        public int UserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Quarter Quarter { get; set; }
        public virtual User User { get; set; }
        public virtual Variety Variety { get; set; }
        public virtual AdvertDetail AdvertDetail { get; set; }

        public virtual ICollection<AdvertEnvironmentFeature> AdvertEnvironmentFeature { get; set; }
        public virtual ICollection<AdvertExteriorFeature> AdvertExteriorFeature { get; set; }
        public virtual ICollection<AdvertInternalFeature> AdvertInternalFeature { get; set; }
        public virtual AdvertOwner AdvertOwner { get; set; }
        public virtual ICollection<Picture> Picture { get; set; }
    }
}
