//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarputGayriMenkul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertExteriorFeature
    {
        public int ID { get; set; }
        public int AdvertID { get; set; }
        public int ExteriorFeatureID { get; set; }
    
        public virtual Advert Advert { get; set; }
    }
}
