//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarputGayriMenkul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertOwner
    {
        public int AdvertID { get; set; }
        public string AdvertOwnerName { get; set; }
        public string AdvertOwnerSurname { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string E_mail { get; set; }
    
        public virtual Advert Advert { get; set; }
    }
}
