//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarputGayriMenkul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public County()
        {
            this.tbl_semt = new HashSet<tbl_semt>();
        }
    
        public short CountyID { get; set; }
        public string CountyName { get; set; }
        public Nullable<short> CityID { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<tbl_semt> tbl_semt { get; set; }
    }
}
