//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarputGayriMenkul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarter
    {
        public Quarter()
        {
            this.Advert = new HashSet<Advert>();
        }
    
        public int QuarterID { get; set; }
        public short SemtID { get; set; }
        public string mahalle_ad { get; set; }
        public Nullable<short> pk_id { get; set; }
    
        public virtual ICollection<Advert> Advert { get; set; }
    }
}
