//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarputGayriMenkul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_semt
    {
        public short SemtID { get; set; }
        public short CountyID { get; set; }
        public string SemtAdi { get; set; }
    
        public virtual County County { get; set; }
    }
}
